# Testing Steps:
# 1. Apply: kubectl apply -f test-export2secret.yaml
# 2. Watch: kubectl get workflowrun test-export2secret -w
# 3. Verify secrets created: kubectl get secrets api-credentials docker-registry-secret database-creds -n default
# 4. Check secret type: kubectl get secret docker-registry-secret -o jsonpath='{.type}'
# 5. Decode api-key: kubectl get secret api-credentials -o jsonpath='{.data.api-key}' | base64 -d
# 6. Check all secret keys: kubectl get secret database-creds -o jsonpath='{.data}' | jq 'keys'
# 7. Cleanup: kubectl delete workflowrun test-export2secret && kubectl delete secret api-credentials docker-registry-secret database-creds
apiVersion: core.oam.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: test-export2secret
  namespace: default
spec:
  workflowSpec:
    steps:
      # Example 1: Generic secret with custom data
      - name: export-api-credentials
        type: export2secret
        properties:
          secretName: api-credentials
          data:
            api-key: "sk-1234567890abcdef"
            api-secret: "secret-token-xyz"
            webhook-url: "https://api.example.com/webhook"
      # Example 2: Docker registry secret
      - name: export-docker-secret
        type: export2secret
        properties:
          secretName: docker-registry-secret
          kind: docker-registry
          dockerRegistry:
            username: myusername
            password: mypassword
            server: "https://index.docker.io/v1/"
      # Example 3: Database credentials
      - name: export-db-credentials
        type: export2secret
        properties:
          secretName: database-creds
          namespace: default
          data:
            username: "admin"
            password: "super-secret-password"
            host: "db.example.com"
            port: "5432"
